version: '3.4'
services:
  firmware:
    image: infinitecoding/platformio-for-ci
    working_dir: /opt
    environment:
      - VERSION=0.0.0
    volumes:
      - platformio:/root/.platformio
      - build:/opt/
      - ./src:/opt/src/
      - ./data:/opt/data/
      - ./lib:/opt/lib/
      - ./platformio.ini:/opt/platformio.ini
    tty: true
    command:
      - pio
      - run
      - -t
      - buildprog
  filesystem:
    image: infinitecoding/platformio-for-ci
    working_dir: /opt
    volumes:
      - platformio:/root/.platformio
      - build:/opt/
      - ./src:/opt/src/
      - ./data:/opt/data/
      - ./lib:/opt/lib/
      - ./platformio.ini:/opt/platformio.ini
    tty: true
    command:
      - pio
      - run
      - -t
      - buildfs
volumes:
  platformio:
  build: