name: Platformio CI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.WEBSERIALPRO_SSH_KEY }}
        submodules: true
    - name: PlatformIO Run
      uses: karniv00l/platformio-run-action@0.1.0
