name: Platformio CI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.WEBSERIALPRO_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: unnecessary
    - name: Configure root account
      run: sudo cp -r /home/runner/.ssh /root/.ssh
    - name: Checkout
      uses: actions/checkout@v3
    - name: PlatformIO Run
      uses: karniv00l/platformio-run-action@0.1.0
